Assistinette o norm atualizado - agora aceita especificar pasta(s) e/ou arquivo(s)

diff --git a/norm b/norm
--- a/norm
+++ b/norm
@@ -13,6 +13,8 @@ print_colored() {
         "greenb") echo -e "\033[1;32m$1\033[0m" ;; # Verde
         "yellowb") echo -e "\033[1;33m$1\033[0m" ;; # Amarelo
         "yellow") echo -e "\033[0;33m$1\033[0m" ;; # Amarelo
+        "blueb") echo -e "\033[1;34m$1\033[0m" ;; # Amarelo
+	"cyanu") echo -e "\033[4;36m$1\033[0m" ;; # Amarelo
         *) echo "$1" ;; # Sem cor
     esac
 }
@@ -24,35 +26,81 @@ if [[ "$1" == "-D" ]]; then
     shift
 fi
 
-DIR="."
-if [[ ! -z "$1" ]]; then
-	DIR="$1"
-fi
 FOUND_ERROR=false
 
-# Rodar norminette e filtrar arquivos com ou sem erro
-for file in $(find "$DIR" -type f \( -name "*.c" -o -name "*.h" \)); do
-    output=$(norminette "$file")
-    
-    if echo "$output" | grep -q "Error"; then
-        # Arquivo com erro (KO)
-	FOUND_ERROR=true
-        if $SHOW_ALL; then
-            print_colored "KO: $file" "yellowb"
-	    print_colored "$output" "yellow"
-        else
-            print_colored "KO: $file" "yellowb"
-	    print_colored "$output" "yellow"
-        fi
-    else
-        # Arquivo sem erro (OK)
-        if $SHOW_ALL; then
-            print_colored "OK: $file" "greenb"
-        fi
-    fi
-done
+run_norm() {
+	local DIR=$1
+	print_colored "> /$DIR:" "cyanu"
+	for file in $(find "$DIR" -type f \( -name "*.c" -o -name "*.h" \)); do
+	    output=$(norminette "$file")
+	    
+	    if echo "$output" | grep -q "Error"; then
+		# Arquivo com erro (KO)
+		FOUND_ERROR=true
+		if $SHOW_ALL; then
+		    print_colored "KO: $file" "yellowb"
+		    print_colored "$output" "yellow"
+		else
+		    print_colored "KO: $file" "yellowb"
+		    print_colored "$output" "yellow"
+		fi
+	    else
+		# Arquivo sem erro (OK)
+		if $SHOW_ALL; then
+		    print_colored "OK: $file" "greenb"
+		fi
+	    fi
+	done
 
-if ! $FOUND_ERROR && ! $SHOW_ALL; then
-	print_colored ">>>>> SUCCESS <<<<<" "greenb"
+	if ! $FOUND_ERROR && ! $SHOW_ALL; then
+		print_colored ">>>>> SUCCESS <<<<<" "greenb"
+	fi
+}
+
+run_norm_file() {
+	local file=$1
+	print_colored "> $file:" "cyanu"
+	output=$(norminette "$file")
+
+	if echo "$output" | grep -q "Error"; then
+		# Arquivo com erro (KO)
+		FOUND_ERROR=true
+		if $SHOW_ALL; then
+		    print_colored "KO: $file" "yellowb"
+		    print_colored "$output" "yellow"
+		else
+		    print_colored "KO: $file" "yellowb"
+		    print_colored "$output" "yellow"
+		fi
+	else
+		# Arquivo sem erro (OK)
+		if $SHOW_ALL; then
+			print_colored "OK: $file" "greenb"
+		fi
+	fi
+
+	if ! $FOUND_ERROR && ! $SHOW_ALL; then
+		print_colored ">>>>> SUCCESS <<<<<" "greenb"
+	fi
+}
+
+if [[ "$#" -eq 0 ]]; then
+	run_norm .
+	exit 1
 fi
 
+i=1
+
+for item in "$@"; do
+	if [ -f "$item" ]; then
+		run_norm_file "$item"
+		echo ""
+	elif [ -d "$item" ]; then
+		run_norm "$item"
+		echo ""
+	fi
+done
+
+printf "\033[F\033[K"
+
+# Rodar norminette e filtrar arquivos com ou sem erro
